name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Trivy GitHub Action to scan the 04_05 directory
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: config
          path: ./04_05
          exit-code: '1'
          severity: 'CRITICAL,HIGH'