name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Trivy GitHub Action to scan the 04_05 directory
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          scan-type: config
          path: ./04_05

      # Upload SARIF results to GitHub Security tab
      - name: Upload Trivy results to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif