# This will be the GitHub Action that will scan our
# infrastructure as code files with Trivy.
name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: config
          exit-code: "0"
          severity: "CRITICAL,HIGH"
