name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run Trivy GitHub Action to scan the 04_05 directory
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: config
          # The exit code to return if vulnerabilities are found
          # This will fail the action if any vulnerabilities are found
          # If you want to ignore vulnerabilities and not fail the action, set exit-code to '0'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'